config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/hello'

  get 'products/new'

  root 'welcome#index'

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection   #we use this because it doesn't require an id

  end

  resources :products do

    resources :favorites, only: [:create, :destroy]

    resources :reviews do
      resources :likes, only: [:create, :destroy]
    end

  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  validates :review_id, uniqueness: {scope: :user_id}

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :review

  def create

    like         = Like.new
    @product      = Product.find params[:product_id]
    like.user    = current_user
    like.review  = review
    respond_to do |format|

      if like.save
        format.html {redirect_to product_path(product), notice: "Thanks for liking!"}
        format.js {render}
      else
        format.html {redirect_to product_path(product), alert: "Already liked!"}
        format.js {render js: "alert('Cant like, please refresh the page!')"}
      end
    end
  end

  def destroy

    @product = Product.find params[:product_id]
    review  = Review.find params[:review_id]
    like    = current_user.likes.find params[:id]
    like.destroy
    respond_to do |format|
      format.html {redirect_to product_path(product), notice: "Like removed!"}
      format.js {render }
    end
  end

  def review
    @review ||= Review.find params[:review_id]
  end

  def liked_by?(user)
    likes.find_by_user_id(user.id).present?
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? && review.liked_by?(current_user) %>
  <%= link_to "Remove Like", product_review_like_path(review.like_for(current_user), product_id: @product.id, review_id: review.id), method: :delete, remote: true %>
<% else %>
  <%= link_to "Like", product_review_likes_path(product_id: @product.id, review_id: review.id), class: "icon-big", method: :post, remote: true   %>
<% end %><br>

<p>Likes: (<%= review.likes.count %>)</p>

app/views/likes/create.js.erb
$("#review-like").html("<%= j render '/likes/like', review: @review %>");

app/views/likes/destroy.js.erb
$("#review-like").html("<%= j render '/likes/like', review: @review %>");