config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/hello'

  get 'products/new'

  root 'welcome#index'

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection   #we use this because it doesn't require an id

  end

  resources :products do

    resources :favorites, only: [:create, :destroy]

    resources :reviews do
      resources :likes, only: [:create, :destroy]
    end

  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  before_validation :default_sale_price

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true
  validates :sale_price, presence: true, numericality: {less_than_or_equal_to: :price}

  belongs_to :category
  belongs_to :user

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  def favorited_by?(user)
    favorites.find_by_user_id(user.id).present?
  end

  def on_sale?
    sale_price < price
  end

  def favorite_for(user)
    favorites.find_by_user_id user if user
  end

  def user_full_name
    user ? user.full_name.titleize : ""
  end

  def default_sale_price
    self.sale_price ||= price
  end

  private

  def titleize_title
    self.title = title.titleize
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]  #should happen first

  before_action(:find_product, {only: [:show, :edit, :update, :destroy]})

    def new
      # we need to define a new 'Product' object in order to be able to
      # properly generate form in Rails
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      @product.user = current_user

      if @product.save
        flash[:notice] = "Product Created!"
        # redirect_to product_path({id: @product.id})
        redirect_to product_path(@product)

      else
        flash[:alert] = "Product didn't save"
        # this will render '/app/views/products/new.html.erb' becasue the default
        # in this action is to render 'app/views/products/create.html.erb'
        render 'new'

      end
    end

    def show
      @product = Product.find params[:id]
      @review = Review.new
      respond_to do |format|
        format.html {render}
        format.json {render json: @product.to_json(include: :reviews)}
        format.xml {render xml: @products.to_xml}
      end
    end

    def index
      @products = Product.all
      respond_to do |format|
        format.html {render}
        format.json {render json: @products.to_json }
      end
    end

    def edit
      @product = Product.find params[:id]
    end

    def update
      if @product.update product_params
        # flash messages can be set either direclty use: flash[:notice] = ".."
        # you can also pass ':notice' or ':alert 'options to the 'redirect_to'
        # method
        redirect_to product_path(@product), notice: "#{@product.title} updated!"
      else
        render 'edit'
      end
    end

    def destroy
      @product = Product.find params[:id]
      @product.destroy
      redirect_to products_path
    end

    private

    def find_product
      @product = Product.find params[:id]
    end

    def product_params
      params.require(:product).permit([:title, :body, :category_id, :price, :sale_price])
    end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= @product.errors.full_messages.join(", ") %>

<%= form_for @product do |f| %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :price%>
    $ <%= f.text_field :price, class:"form-control"  %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control"  %>
  </fieldset>

<%= f.submit class: "btn btn-primary" %>
<% end%>

app/views/products/edit.html.erb
<h1>Edit Products</h1>

<%#If you give the form_for helper an ActiveRecord object that is persisted then %>
<%#the generated form will have an action that submits to 'product_path(@product)'%>
<%# where @product is the ActiveRecord object htat you passed to the form %>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>
<table class="table table-bordered table-hover">

  <thead class="">
    <tr>
      <th width=80px>Product Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Sale Price</th>

      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>

    <tr>
      <td><%= link_to product.title, product_path(product) %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.sale_price %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product_path(product), method: :delete,
                                                  data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
    <%end%>
  </tbody>

</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%=@product.title.titleize %></h1>
<h3><%= @product.description %></h3>
<p>Regular Price: $<%= @product.price %></p>
<p>Sale Price: $<%= @product.price %></p>
<p>Created by: <%= @product.user_full_name %></p>

<br>
<%= link_to "Edit", edit_product_path(@product)%>
<%= link_to "Delete", product_path(@product),
method: :delete,
data: {confirm: 'Are you sure?'} %>
<br>
<br>
<p>
  Favorites: (<%= @product.favorites.count %>)
</p>

<% if user_signed_in? && @product.favorited_by?(current_user) %>
  <%= link_to "Remove Favorite", product_favorite_path(@product, @product.favorite_for(current_user)), method: :delete %>
<% else %>
  <%= link_to "Favorite", product_favorites_path(@product), class: "icon-big", method: :post   %>
<% end %>
<br><br>



<errors><%= @review.errors.full_messages.join(", ") %></errors>

<h2>Add a review:</h2>
<div id="review-form">
  <%= render '/reviews/form', review: @review %>
</div>

<h2>Reviews:</h2>
<div id="reviews">
  <% @product.reviews.each do |rev| %>
    <%= render "/reviews/review", review: rev %>
  <% end %>
</div>