config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/hello'

  get 'products/new'

  root 'welcome#index'

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection   #we use this because it doesn't require an id

  end

  resources :products do

    resources :favorites, only: [:create, :destroy]

    resources :reviews do
      resources :likes, only: [:create, :destroy]
    end

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.create(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html  {redirect_to product_path(@product), notice: "Review Saved!"}
        format.js {render :create_success}
      else
        flash[:alert] = "Review not saved"
        format.html {render 'products/show'}
        format.js { render js: "alert('failure');"}
      end
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy
    respond_to do |format|
      format.html {redirect_to product_path(@product), notice: "Review Deleted!"}
      format.js {render}
    end
  end

  def liked_by?(user)
    likes.find_by_user_id(user.id).present?
  end

  private

  def user_like
    @user_like ||= @review.like_for(current_user)
  end


  def review_params
    params.require(:review).permit(:body, :stars)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for [@product, @product.reviews.build], remote: true do |f| %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :stars %><br>
    <%= f.text_field :stars %>
  </p>
  <p>
    <%= f.submit data: {disable_with: "Submitting..."}, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<% if review.persisted? %>
<div id="<%= dom_id(review) %>" style="<%= style if defined?(style)%>">
<ul>
  <li>
<p><%= review.body %></p>
<p>Created by:  <%= review.user ? review.user.full_name.titleize : "" %></p>
<p>Rating:  <%= review.stars %> Star(s)</p>

  <%= link_to 'Destroy Review', [review.product, review],
               method: :delete,
               data: { confirm: 'Are you sure?' },
               remote: true %>

<br>

<div id="review-like">
  <%= render "/likes/like", review: review%>
</div>

</li>
</ul>
<% end %>
</div>

app/views/reviews/create_failure.js.erb
$("#review-form").html("<%= j render 'form'%>");

app/views/reviews/create_success.js.erb
$('#reviews').prepend("<%= j render '/reviews/review', review: @review, style: 'display: none' %>");
$('#review-form').html("<%= j render '/reviews/form', review: Review.new %>");
$("#<%= dom_id(@review) %>").slideDown(1000);

app/views/reviews/destroy.js.erb
$("#<%= dom_id(@review) %>").fadeOut(1000, function() {
  $(this).remove();
});

app/views/reviews/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @products.body%>
</p>


<h2>Add a review:</h2>
<%= form_for ([@product, @product.reviews.build]) do |f| %>
<p>
 <%= f.label :body %><br>
 <%= f.text_area :body, rows:5, cols:40 %>
</p>
<p>
  <%= f.submit class: "btn btn-primary" %>
</p>
<% end %>


<%= link_to 'Edit', edit_product_path(@product) %>|
<%= link_to 'Back', products_path %>